platform :ios, '9.0'

target 'MQTTchat' do
  use_frameworks!

  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal', '~> 1.0.1.18'
  pod 'JSQMessagesViewController'
  pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git'
  pod 'Alamofire', '~> 4.0'
end
