/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: ChatModel.proto
 *
 */

import Foundation
import SwiftProtobuf


public struct ChatMessage: ProtobufGeneratedMessage {
  public var swiftClassName: String {return "ChatMessage"}
  public var protoMessageName: String {return "ChatMessage"}
  public var protoPackageName: String {return ""}
  public var jsonFieldNames: [String: Int] {return [
    "timestamp": 1,
    "senderId": 2,
    "name": 3,
    "message": 4,
  ]}
  public var protoFieldNames: [String: Int] {return [
    "timestamp": 1,
    "senderId": 2,
    "name": 3,
    "message": 4,
  ]}

  var unknown = ProtobufUnknownStorage()

  public var timestamp: Int64 = 0

  public var senderId: String = ""

  public var name: String = ""

  public var message: String = ""

  public init() {}

  public init(timestamp: Int64 = 0,
    senderId: String = "",
    name: String = "",
    message: String = "")
  {
    self.timestamp = timestamp
    self.senderId = senderId
    self.name = name
    self.message = message
  }

  public mutating func _protoc_generated_decodeField(setter: inout ProtobufFieldDecoder, protoFieldNumber: Int) throws -> Bool {
    let handled: Bool
    switch protoFieldNumber {
    case 1: handled = try setter.decodeRequiredField(fieldType: ProtobufInt64.self, value: &timestamp)
    case 2: handled = try setter.decodeRequiredField(fieldType: ProtobufString.self, value: &senderId)
    case 3: handled = try setter.decodeRequiredField(fieldType: ProtobufString.self, value: &name)
    case 4: handled = try setter.decodeRequiredField(fieldType: ProtobufString.self, value: &message)
    default:
      handled = false
    }
    if handled {
        return true
    } else {
        return try unknown.decodeField(setter: &setter)
    }
  }

  public func _protoc_generated_traverse(visitor: inout ProtobufVisitor) throws {
    try visitor.visitSingularField(fieldType: ProtobufInt64.self, value: timestamp, protoFieldNumber: 1, protoFieldName: "timestamp", jsonFieldName: "timestamp", swiftFieldName: "timestamp")
    try visitor.visitSingularField(fieldType: ProtobufString.self, value: senderId, protoFieldNumber: 2, protoFieldName: "senderId", jsonFieldName: "senderId", swiftFieldName: "senderId")
    try visitor.visitSingularField(fieldType: ProtobufString.self, value: name, protoFieldNumber: 3, protoFieldName: "name", jsonFieldName: "name", swiftFieldName: "name")
    try visitor.visitSingularField(fieldType: ProtobufString.self, value: message, protoFieldNumber: 4, protoFieldName: "message", jsonFieldName: "message", swiftFieldName: "message")
    unknown.traverse(visitor: &visitor)
  }

  public var _protoc_generated_isEmpty: Bool {
    if timestamp != 0 {return false}
    if senderId != "" {return false}
    if name != "" {return false}
    if message != "" {return false}
//    if !unknown.isEmpty {return false}
    return true
  }

  public func _protoc_generated_isEqualTo(other: ChatMessage) -> Bool {
    if timestamp != other.timestamp {return false}
    if senderId != other.senderId {return false}
    if name != other.name {return false}
    if message != other.message {return false}
    if unknown != other.unknown {return false}
    return true
  }
}
